const {
  createPrescription,
  getPatientPrescriptions,
  getDoctorPrescriptions,
  getAllPrescriptions,
} = require("./service");
const { logAction } = require("../audit/service");
const LabOrder = require("../lab/models/labOrder.model");
const Bill = require("../billing/models/bill.model");

const User = require("../users/models/user.model");
const { createOrder } = require("../pharmacy-orders/service");

const createPrescriptionController = async (req, res, next) => {
  try {
    const { patientId, appointmentId, medicines, notes, deliveryType, wardNumber } = req.body;

    // 1. If Ward Delivery is selected, check if patient is admitted
    if (deliveryType === "WARD") {
      const patient = await User.findById(patientId);
      if (!patient || !patient.admission?.isAdmitted) {
        return res.status(400).json({
          success: false,
          message: "Patient is not admitted to the hospital. Ward delivery is not possible."
        });
      }
      
      // Optional: Check if patient is in the same hospital as the doctor
      const doctor = await User.findById(req.user.id);
      if (patient.admission.hospitalName !== doctor?.hospitalName) {
        return res.status(400).json({
          success: false,
          message: `Patient is admitted to ${patient.admission.hospitalName}, not your hospital.`
        });
      }
    }

    const prescription = await createPrescription({
      patientId,
      doctorId: req.user.id,
      appointmentId,
      medicines,
      notes,
      deliveryType: deliveryType || "PHARMACY",
      wardNumber: deliveryType === "WARD" ? wardNumber : null
    });

    // Fetch patient name for log
    const patient = await User.findById(patientId).select("name");

    // Audit Log
    await logAction({
      userId: req.user.id,
      role: req.user.role,
      action: "CREATE_PRESCRIPTION",
      module: "PRESCRIPTIONS",
      targetId: prescription._id,
      ipAddress: req.ip,
      details: { 
        patientId, 
        patientName: patient?.name || "Unknown Patient",
        appointmentId, 
        deliveryType 
      }
    });

    // Get doctor's hospital name
    const doctor = await User.findById(req.user.id);

    // Automatically create Pharmacy Order
    await createOrder({
      patientId,
      prescriptionId: prescription._id,
      medicines: medicines.map(m => m.name), 
      billAmount: 0, 
      doctorId: req.user.id,
      isAdmitted: deliveryType === "WARD",
      wardNumber: deliveryType === "WARD" ? (wardNumber || prescription.wardNumber) : null,
      hospitalName: doctor?.hospitalName,
      hospitalAddress: doctor?.hospitalAddress
    });

    console.log("Pharmacy order auto-created from prescription. Bill will be generated by the pharmacist.");

    res.status(201).json({
      success: true,
      data: prescription
    });
  } catch (error) {
    next(error);
  }
};

const getMyPrescriptions = async (req, res, next) => {
  try {
    const prescriptions = await getPatientPrescriptions(req.user.id);

    res.json({
      success: true,
      data: prescriptions,
    });
  } catch (error) {
    next(error);
  }
};

const getDoctorPrescriptionsController = async (req, res, next) => {
  try {
    const prescriptions = await getDoctorPrescriptions(req.user.id);

    res.json({
      success: true,
      data: prescriptions,
    });
  } catch (error) {
    next(error);
  }
};

const getAllPrescriptionsController = async (req, res, next) => {
  try {
    const prescriptions = await getAllPrescriptions();

    res.json({
      success: true,
      data: prescriptions,
    });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  createPrescription: createPrescriptionController,
  getMyPrescriptions,
  getDoctorPrescriptions: getDoctorPrescriptionsController,
  getAllPrescriptions: getAllPrescriptionsController,
};
