const dietData = {
    "Hemoglobin": {
        "morning": [
            "Oatmeal with berries and nuts (150g)",
            "Tofu scramble with vegetables (150g)",
            "Tofu scramble with veggies (150g)",
            "Greek yogurt with granola and fruit (100g)",
            "Overnight oats with fruit and chia seeds (100g)",
            "Scrambled eggs with whole-wheat toast and avocado (150g)",
            "Spinach and Beetroot smoothie (250ml)",
            "Pomegranate and Apple salad (150g)",
            "Soaked Raisins and Almonds (50g)",
            "Amla (Gooseberry) juice (100ml)"
        ],
        "afternoon": [
            "Chicken breast with brown rice and vegetables (200g)",
            "Vegan chili with brown rice (150g)",
            "Black bean burger on a whole-wheat bun (150g)",
            "Lentil and vegetable curry (150g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Grilled chicken salad with mixed greens (200g)",
            "Palak (Spinach) Paneer with 2 Multigrain Chapatis (250g)",
            "Methi (Fenugreek) Dal with 1/2 cup Brown Rice (200g)",
            "Grilled Liver (if non-veg) or Tofu (150g)",
            "Soybean chunks curry (100g) with 1 Chapati"
        ],
        "snacks": [
            "Greek yogurt with fruit (100g)",
            "Fruit and nut mix (100g)",
            "Mixed nuts (150g)",
            "Apple with almond butter (150g)",
            "Trail mix (150g)",
            "Hummus and veggie wrap (150g)",
            "Roasted Makhana (Fox Nuts) (50g)",
            "Dates and Walnuts (50g)",
            "Fresh Pomegranate juice (200ml)",
            "Jaggery and Roasted Chana (50g)"
        ],
        "night": [
            "Steak with sweet potato and broccoli (200g)",
            "Lentil and vegetable stew (150g)",
            "Salmon with roasted vegetables (200g)",
            "Vegetable stir-fry with brown rice (150g)",
            "Vegan chili (150g)",
            "Chickpea curry with brown rice (150g)",
            "Beetroot and vegetable soup (200ml)",
            "Moong Dal Khichdi with lots of veggies (250g)",
            "Grilled Fish or Chicken with lemon (150g)",
            "Masoor Dal with 1/2 cup Quinoa (200g)"
        ]
    },
    "Blood Sugar (F)": {
        "morning": [
            "Tofu scramble with veggies (150g)",
            "Tofu and veggie breakfast burrito (150g)",
            "Greek yogurt with granola and fruit (100g)",
            "Scrambled eggs with whole wheat toast and avocado (150g)",
            "Protein pancakes with fruit and nuts (100g)",
            "Tofu and chickpea scramble (150g)",
            "Overnight oats with fruit and chia seeds (100g)",
            "Oatmeal with berries and nuts (150g)",
            "Wholegrain toast with avocado (150g)",
            "Greek yogurt with granola (100g)",
            "Tofu and vegetable stir-fry (150g)",
            "Eggs with wholegrain toast (150g)",
            "Tofu scramble with vegetables (150g)",
            "Eggs with whole wheat toast and avocado (150g)",
            "Greek yogurt with fruit and granola (100g)",
            "Oatmeal with berries and plant-based milk (150g)",
            "Oatmeal with fruit and nuts (100g)",
            "Tofu scramble with whole-wheat toast (150g)",
            "Tofu and vegetable breakfast burrito (150g)",
            "Pancakes with fruit and syrup (100g)",
            "Scrambled eggs with whole-wheat toast (150g)",
            "Greek yogurt with berries and granola (100g)",
            "Tofu scramble with spinach and avocado toast (150g)",
            "Eggs with whole-wheat toast (150g)",
            "Scrambled eggs with bacon and whole-wheat toast (150g)",
            "Eggs with whole-wheat toast and avocado (150g)",
            "Scrambled eggs with vegetables and whole-wheat toast (150g)",
            "Scrambled eggs with whole-wheat toast and avocado (150g)",
            "Tofu scramble with veggies and whole-wheat toast (150g)",
            "Overnight oats with fruit and nuts (100g)",
            "Yogurt with fruit and granola (100g)",
            "Scrambled eggs with whole wheat toast and fruit (100g)",
            "Eggs with whole-wheat toast and bacon (150g)",
            "Scrambled tofu with whole-wheat toast and avocado (150g)",
            "Tofu scramble with vegetables and whole-wheat toast (150g)",
            "Scrambled eggs with whole wheat toast (150g)",
            "Tofu and vegetable scramble with whole wheat toast (150g)",
            "Tofu and vegetable stir-fry with brown rice (150g)",
            "Tofu scramble with vegetables and avocado (150g)",
            "Tofu breakfast burrito with whole-wheat tortilla (150g)"
        ],
        "afternoon": [
            "Lentil soup with whole wheat bread (150g)",
            "Black bean burger on a whole wheat bun (150g)",
            "Chicken and vegetable stir-fry (200g)",
            "Quinoa salad with chickpeas and vegetables (150g)",
            "Lentil pasta with vegetables (150g)",
            "Chicken breast with brown rice and vegetables (200g)",
            "Lentil burger with sweet potato fries (150g)",
            "Grilled chicken salad with mixed greens (200g)",
            "Black bean salad (150g)",
            "Tuna salad sandwich on wholegrain bread (150g)",
            "Lentil and vegetable stew (150g)",
            "Lentil soup with wholegrain bread (150g)",
            "Chicken breast with brown rice (200g)",
            "Turkey sandwich on whole wheat bread with vegetables (150g)",
            "Tuna salad with whole wheat bread (150g)",
            "Vegan lentil stew with whole wheat bread (150g)",
            "Lentil and vegetable curry with brown rice (150g)",
            "Vegetarian chili with whole wheat bread (150g)",
            "Chicken salad sandwich on whole wheat bread (200g)",
            "Chicken breast salad with vegetables (200g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Black bean burger on a whole-wheat bun (150g)",
            "Chicken breast salad with mixed greens (200g)",
            "Grilled chicken sandwich with whole-wheat bread (200g)",
            "Tuna salad sandwich with whole-wheat bread (150g)",
            "Chicken salad sandwich with mixed greens (200g)",
            "Chicken Caesar salad (200g)",
            "Chickpea salad sandwich with whole-wheat bread (150g)",
            "Grilled salmon with roasted vegetables (200g)",
            "Vegetarian chili with a side salad (150g)",
            "Black bean burger with sweet potato fries (150g)",
            "Chicken breast with quinoa and steamed vegetables (200g)",
            "Vegetable stir-fry with brown rice (150g)",
            "Black bean burger with whole-wheat bun and salad (150g)",
            "Lentil soup with whole grain bread (150g)",
            "Chicken breast with brown rice and steamed vegetables (200g)",
            "Turkey sandwich on whole grain bread (150g)",
            "Tuna salad with whole grain bread (150g)",
            "Black bean soup with whole wheat bread (150g)",
            "Chicken breast with roasted vegetables (200g)"
        ],
        "snacks": [
            "Apple with almond butter (150g)",
            "Trail mix (150g)",
            "Banana with peanut butter (150g)",
            "Fruit and nut mix (100g)",
            "Hummus and veggie wrap (150g)",
            "Protein shake (150g)",
            "Energy bar (150g)",
            "Fruit and veggie sticks (100g)",
            "Greek yogurt with fruit (100g)",
            "Fruit salad with yogurt (100g)",
            "Popcorn (150g)",
            "Smoothie with protein powder (150g)",
            "Protein bar (150g)",
            "Trail mix with nuts and dried fruit (100g)",
            "Greek yogurt with fruit and granola (100g)",
            "Mixed nuts and seeds (150g)",
            "Apple with peanut butter (150g)",
            "Banana with almond butter (150g)",
            "Fruit smoothie (100g)",
            "Apple slices with almond butter (150g)",
            "Fruit and cheese (100g)",
            "Fruit and yogurt (100g)",
            "Fruit salad with nuts (100g)",
            "Mixed nuts (150g)",
            "Smoothie with protein powder and fruit (100g)",
            "Trail mix with almonds and dried fruit (100g)",
            "Fruit salad with nuts and seeds (100g)",
            "Protein shake with banana (150g)",
            "Trail mix with dried fruit and nuts (100g)",
            "Apple slices with peanut butter (150g)",
            "Vegetable sticks with hummus (150g)",
            "Hummus with vegetables (150g)",
            "Greek yogurt with berries (100g)",
            "Trail mix with nuts and dried fruits (100g)",
            "Low-fat Greek yogurt with berries (100g)",
            "Raw vegetables and hummus (150g)",
            "Celery sticks with peanut butter (150g)",
            "Fruit salad (100g)",
            "Trail mix with almonds and dried cranberries (150g)",
            "Protein shake with fruit (100g)"
        ],
        "night": [
            "Vegetable stir-fry with brown rice (150g)",
            "Lentil and vegetable curry (150g)",
            "Turkey chili with brown rice (150g)",
            "Vegetarian chili with cornbread (150g)",
            "Vegan stir-fry with brown rice (150g)",
            "Steak with sweet potato and broccoli (200g)",
            "Vegan chili with cornbread (150g)",
            "Vegan pasta with vegetables and sauce (150g)",
            "Salmon with roasted vegetables (200g)",
            "Vegetable stir-fry with tofu (150g)",
            "Chicken breast with steamed vegetables (200g)",
            "Vegan chili (150g)",
            "Steak with roasted vegetables (200g)",
            "Vegetarian chili with brown rice (150g)",
            "Chicken and vegetable stir-fry with brown rice (200g)",
            "Chicken breast with sweet potato and green beans (200g)",
            "Vegan pasta with vegetables and tomato sauce (150g)",
            "Tofu stir-fry with brown rice and vegetables (150g)",
            "Tofu stir-fry with brown rice noodles (150g)",
            "Vegetable stir-fry with tofu and brown rice (150g)",
            "Black bean burgers with salad (150g)",
            "Lentil pasta with marinara sauce (150g)",
            "Turkey meatballs with steamed vegetables (150g)",
            "Chicken stir-fry with brown rice (200g)",
            "Chicken breast with roasted vegetables (200g)",
            "Beef stew with brown rice (150g)",
            "Vegan chili with brown rice (150g)",
            "Fish with roasted vegetables (150g)",
            "Grilled salmon with roasted vegetables (200g)",
            "Lentil stew with brown rice (150g)",
            "Tuna with quinoa and roasted vegetables (150g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Vegetarian lasagna with salad (150g)",
            "Steak with baked potato and broccoli (200g)",
            "Black bean burgers with sweet potato fries (150g)",
            "Lentil and vegetable stew (150g)",
            "Tofu stir-fry with brown rice (150g)",
            "Beef stew with whole grain bread (150g)",
            "Salmon with steamed vegetables (200g)",
            "Steak with sweet potato and green beans (200g)"
        ]
    },
    "Total Cholesterol": {
        "morning": [
            "Tofu scramble with veggies (150g)",
            "Tofu and veggie breakfast burrito (150g)",
            "Greek yogurt with granola and fruit (100g)",
            "Scrambled eggs with whole wheat toast and avocado (150g)",
            "Tofu and chickpea scramble (150g)",
            "Overnight oats with fruit and chia seeds (100g)",
            "Oatmeal with berries and nuts (150g)",
            "Wholegrain toast with avocado (150g)",
            "Greek yogurt with granola (100g)",
            "Tofu and vegetable stir-fry (150g)",
            "Eggs with wholegrain toast (150g)",
            "Tofu scramble with vegetables (150g)",
            "Oatmeal with protein powder and fruit (100g)",
            "Eggs with whole wheat toast and avocado (150g)",
            "Greek yogurt with fruit and granola (100g)",
            "Oatmeal with berries and plant-based milk (150g)",
            "Oatmeal with fruit and nuts (100g)",
            "Tofu scramble with whole-wheat toast (150g)",
            "Tofu and vegetable breakfast burrito (150g)",
            "Pancakes with fruit and syrup (100g)",
            "Scrambled eggs with whole-wheat toast (150g)",
            "Greek yogurt with berries and granola (100g)",
            "Tofu scramble with spinach and avocado toast (150g)",
            "Eggs with whole-wheat toast (150g)",
            "Scrambled eggs with bacon and whole-wheat toast (150g)",
            "Eggs with whole-wheat toast and avocado (150g)",
            "Scrambled eggs with vegetables and whole-wheat toast (150g)",
            "Tofu scramble with veggies and whole-wheat toast (150g)",
            "Overnight oats with fruit and nuts (100g)",
            "Yogurt with fruit and granola (100g)",
            "Scrambled eggs with whole wheat toast and fruit (100g)",
            "Eggs with whole-wheat toast and bacon (150g)",
            "Scrambled tofu with whole-wheat toast and avocado (150g)",
            "Tofu scramble with vegetables and whole-wheat toast (150g)",
            "Scrambled eggs with whole wheat toast (150g)",
            "Tofu and vegetable scramble with whole wheat toast (150g)",
            "Tofu and vegetable stir-fry with brown rice (150g)",
            "Tofu scramble with vegetables and avocado (150g)",
            "Tofu breakfast burrito with whole-wheat tortilla (150g)",
            "Scrambled tofu with spinach and tomato (150g)"
        ],
        "afternoon": [
            "Lentil soup with whole wheat bread (150g)",
            "Black bean burger on a whole wheat bun (150g)",
            "Chicken and vegetable stir-fry (200g)",
            "Quinoa salad with chickpeas and vegetables (150g)",
            "Lentil pasta with vegetables (150g)",
            "Lentil burger with sweet potato fries (150g)",
            "Grilled chicken salad with mixed greens (200g)",
            "Black bean salad (150g)",
            "Tuna salad sandwich on wholegrain bread (150g)",
            "Lentil and vegetable stew (150g)",
            "Lentil soup with wholegrain bread (150g)",
            "Chicken breast with brown rice (200g)",
            "Chicken breast with sweet potato and broccoli (200g)",
            "Turkey sandwich on whole wheat bread with vegetables (150g)",
            "Tuna salad with whole wheat bread (150g)",
            "Vegan lentil stew with whole wheat bread (150g)",
            "Lentil and vegetable curry with brown rice (150g)",
            "Vegetarian chili with whole wheat bread (150g)",
            "Chicken salad sandwich on whole wheat bread (200g)",
            "Chicken breast salad with vegetables (200g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Black bean burger on a whole-wheat bun (150g)",
            "Chicken breast salad with mixed greens (200g)",
            "Grilled chicken sandwich with whole-wheat bread (200g)",
            "Tuna salad sandwich with whole-wheat bread (150g)",
            "Chicken salad sandwich with mixed greens (200g)",
            "Chicken Caesar salad (200g)",
            "Chickpea salad sandwich with whole-wheat bread (150g)",
            "Grilled salmon with roasted vegetables (200g)",
            "Vegetarian chili with a side salad (150g)",
            "Black bean burger with sweet potato fries (150g)",
            "Vegetable stir-fry with brown rice (150g)",
            "Black bean burger with whole-wheat bun and salad (150g)",
            "Lentil soup with whole grain bread (150g)",
            "Chicken breast with brown rice and steamed vegetables (200g)",
            "Turkey sandwich on whole grain bread (150g)",
            "Tuna salad with whole grain bread (150g)",
            "Black bean soup with whole wheat bread (150g)",
            "Chicken breast with roasted vegetables (200g)",
            "Lentil and vegetable soup with whole-wheat bread (150g)"
        ],
        "snacks": [
            "Apple with almond butter (150g)",
            "Trail mix (150g)",
            "Banana with peanut butter (150g)",
            "Fruit and nut mix (100g)",
            "Hummus and veggie wrap (150g)",
            "Energy bar (150g)",
            "Fruit and veggie sticks (100g)",
            "Greek yogurt with fruit (100g)",
            "Fruit salad with yogurt (100g)",
            "Popcorn (150g)",
            "Smoothie with protein powder (150g)",
            "Protein bar (150g)",
            "Protein shake (150g)",
            "Trail mix with nuts and dried fruit (100g)",
            "Greek yogurt with fruit and granola (100g)",
            "Mixed nuts and seeds (150g)",
            "Apple with peanut butter (150g)",
            "Banana with almond butter (150g)",
            "Fruit smoothie (100g)",
            "Apple slices with almond butter (150g)",
            "Fruit and cheese (100g)",
            "Fruit and yogurt (100g)",
            "Fruit salad with nuts (100g)",
            "Mixed nuts (150g)",
            "Smoothie with protein powder and fruit (100g)",
            "Trail mix with almonds and dried fruit (100g)",
            "Fruit salad with nuts and seeds (100g)",
            "Trail mix with dried fruit and nuts (100g)",
            "Apple slices with peanut butter (150g)",
            "Vegetable sticks with hummus (150g)",
            "Hummus with vegetables (150g)",
            "Greek yogurt with berries (100g)",
            "Trail mix with nuts and dried fruits (100g)",
            "Low-fat Greek yogurt with berries (100g)",
            "Raw vegetables and hummus (150g)",
            "Celery sticks with peanut butter (150g)",
            "Fruit salad (100g)",
            "Protein shake with banana (150g)",
            "Carrot sticks with hummus (150g)",
            "String cheese with crackers (150g)"
        ],
        "night": [
            "Vegetable stir-fry with brown rice (150g)",
            "Lentil and vegetable curry (150g)",
            "Turkey chili with brown rice (150g)",
            "Vegetarian chili with cornbread (150g)",
            "Vegan stir-fry with brown rice (150g)",
            "Vegan chili with cornbread (150g)",
            "Vegan pasta with vegetables and sauce (150g)",
            "Salmon with roasted vegetables (200g)",
            "Vegetable stir-fry with tofu (150g)",
            "Chicken breast with steamed vegetables (200g)",
            "Vegan chili (150g)",
            "Steak with roasted vegetables (200g)",
            "Vegetarian chili with brown rice (150g)",
            "Chicken and vegetable stir-fry with brown rice (200g)",
            "Chicken breast with sweet potato and green beans (200g)",
            "Vegan pasta with vegetables and tomato sauce (150g)",
            "Tofu stir-fry with brown rice and vegetables (150g)",
            "Tofu stir-fry with brown rice noodles (150g)",
            "Vegetable stir-fry with tofu and brown rice (150g)",
            "Black bean burgers with salad (150g)",
            "Lentil pasta with marinara sauce (150g)",
            "Turkey meatballs with steamed vegetables (150g)",
            "Chicken stir-fry with brown rice (200g)",
            "Chicken breast with roasted vegetables (200g)",
            "Beef stew with brown rice (150g)",
            "Vegan chili with brown rice (150g)",
            "Fish with roasted vegetables (150g)",
            "Grilled salmon with roasted vegetables (200g)",
            "Lentil stew with brown rice (150g)",
            "Tuna with quinoa and roasted vegetables (150g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Vegetarian lasagna with salad (150g)",
            "Black bean burgers with sweet potato fries (150g)",
            "Lentil and vegetable stew (150g)",
            "Tofu stir-fry with brown rice (150g)",
            "Beef stew with whole grain bread (150g)",
            "Salmon with steamed vegetables (200g)",
            "Steak with sweet potato and green beans (200g)",
            "Black bean burgers on whole-wheat buns (150g)",
            "Steak with mashed potatoes and green beans (200g)"
        ]
    },
    "Protein": {
        "morning": [],
        "afternoon": [],
        "snacks": [],
        "night": []
    },
    "Calcium": {
        "morning": [
            "Overnight oats with fruit and chia seeds (100g)",
            "Oatmeal with berries and nuts (150g)",
            "Tofu scramble with veggies (150g)",
            "Greek yogurt with granola and fruit (100g)",
            "Scrambled eggs with whole-wheat toast and avocado (150g)",
            "Tofu scramble with vegetables (150g)"
        ],
        "afternoon": [
            "Lentil and vegetable curry (150g)",
            "Chicken breast with brown rice and vegetables (200g)",
            "Black bean burger on a whole-wheat bun (150g)",
            "Grilled chicken salad with mixed greens (200g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Vegan chili with brown rice (150g)"
        ],
        "snacks": [
            "Hummus and veggie wrap (150g)",
            "Greek yogurt with fruit (100g)",
            "Trail mix (150g)",
            "Mixed nuts (150g)",
            "Apple with almond butter (150g)",
            "Fruit and nut mix (100g)"
        ],
        "night": [
            "Lentil and vegetable stew (150g)",
            "Steak with sweet potato and broccoli (200g)",
            "Chickpea curry with brown rice (150g)",
            "Salmon with roasted vegetables (200g)",
            "Vegan chili (150g)",
            "Vegetable stir-fry with brown rice (150g)"
        ]
    },
    "Vitamin B12": {
        "morning": [
            "Greek yogurt with granola and fruit (100g)",
            "Oatmeal with berries and nuts (150g)",
            "Overnight oats with fruit and chia seeds (100g)",
            "Tofu scramble with veggies (150g)",
            "Scrambled eggs with whole-wheat toast and avocado (150g)",
            "Tofu scramble with vegetables (150g)"
        ],
        "afternoon": [
            "Black bean burger on a whole-wheat bun (150g)",
            "Grilled chicken salad with mixed greens (200g)",
            "Lentil and vegetable curry (150g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Vegan chili with brown rice (150g)",
            "Chicken breast with brown rice and vegetables (200g)"
        ],
        "snacks": [
            "Trail mix (150g)",
            "Mixed nuts (150g)",
            "Fruit and nut mix (100g)",
            "Apple with almond butter (150g)",
            "Hummus and veggie wrap (150g)",
            "Greek yogurt with fruit (100g)"
        ],
        "night": [
            "Vegetable stir-fry with brown rice (150g)",
            "Steak with sweet potato and broccoli (200g)",
            "Vegan chili (150g)",
            "Chickpea curry with brown rice (150g)",
            "Lentil and vegetable stew (150g)",
            "Salmon with roasted vegetables (200g)"
        ]
    },
    "Vitamin D": {
        "morning": [
            "Greek yogurt with granola and fruit (100g)",
            "Oatmeal with berries and nuts (150g)",
            "Overnight oats with fruit and chia seeds (100g)",
            "Tofu scramble with veggies (150g)",
            "Scrambled eggs with whole-wheat toast and avocado (150g)",
            "Tofu scramble with vegetables (150g)"
        ],
        "afternoon": [
            "Black bean burger on a whole-wheat bun (150g)",
            "Grilled chicken salad with mixed greens (200g)",
            "Lentil and vegetable curry (150g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Vegan chili with brown rice (150g)",
            "Chicken breast with brown rice and vegetables (200g)"
        ],
        "snacks": [
            "Trail mix (150g)",
            "Mixed nuts (150g)",
            "Fruit and nut mix (100g)",
            "Apple with almond butter (150g)",
            "Hummus and veggie wrap (150g)",
            "Greek yogurt with fruit (100g)"
        ],
        "night": [
            "Vegetable stir-fry with brown rice (150g)",
            "Steak with sweet potato and broccoli (200g)",
            "Vegan chili (150g)",
            "Chickpea curry with brown rice (150g)",
            "Lentil and vegetable stew (150g)",
            "Salmon with roasted vegetables (200g)"
        ]
    },
    "general wellness": {
        "morning": [
            "Oatmeal with berries and nuts (150g)",
            "Tofu and veggie breakfast burrito (150g)",
            "Tofu scramble with vegetables (150g)",
            "Oatmeal with protein powder and fruit (100g)",
            "Greek yogurt with berries and granola (100g)",
            "Tofu scramble with vegetables and avocado (150g)",
            "Tofu scramble with spinach and avocado (150g)",
            "Scrambled eggs with whole wheat toast and fruit (100g)",
            "Greek yogurt with fruit and granola (100g)",
            "Overnight oats with fruit and chia seeds (100g)",
            "Scrambled eggs with avocado and whole-wheat toast (150g)",
            "Overnight oats with chia seeds and fruit (100g)",
            "Tofu scramble with whole-wheat toast (150g)",
            "Quinoa porridge with fruit and nuts (100g)",
            "Tofu scramble with vegetables and whole-wheat toast (150g)",
            "Oatmeal with protein powder and berries (150g)",
            "Pancakes with fruit and syrup (100g)",
            "Eggs with whole-wheat toast and avocado (150g)",
            "Greek yogurt with berries and nuts (100g)",
            "Tofu scramble with whole wheat toast and avocado (150g)",
            "Greek yogurt with berries and almonds (100g)",
            "Eggs with whole-wheat toast and bacon (150g)",
            "Tofu and vegetable stir-fry with brown rice (150g)",
            "Scrambled eggs with whole-wheat toast and avocado (150g)",
            "Greek Yogurt with berries and granola (100g)",
            "Tofu omelet with spinach (150g)",
            "Greek yogurt with protein powder and fruit (100g)",
            "Tofu scramble with vegetables and whole wheat toast (150g)",
            "Protein pancakes with fruit and syrup (100g)",
            "Protein smoothie with fruit and spinach (100g)",
            "Yogurt parfait with granola and fruit (100g)",
            "Tofu scramble with whole-wheat toast and vegetables (150g)",
            "3 eggs with whole-wheat toast and avocado (150g)",
            "Tofu scramble with avocado and whole-wheat toast (150g)",
            "Scrambled eggs with whole wheat toast (150g)",
            "Quinoa porridge with berries and nuts (150g)",
            "Tofu scramble with whole-wheat toast and avocado (150g)",
            "Overnight oats with berries and nuts (150g)",
            "Tofu scramble with avocado and whole wheat toast (150g)",
            "Oatmeal with fruit and nuts (100g)"
        ],
        "afternoon": [
            "Grilled chicken salad with mixed greens (200g)",
            "Black bean burger on a whole wheat bun (150g)",
            "Lentil soup with wholegrain bread (150g)",
            "Black bean burger on a wholegrain bun (150g)",
            "Grilled chicken breast with brown rice (200g)",
            "Salmon salad with mixed greens and avocado (200g)",
            "Vegan lentil stew with whole wheat bread (150g)",
            "Chicken breast with sweet potato and broccoli (200g)",
            "Lentil soup with whole wheat bread (150g)",
            "Quinoa salad with chickpeas and vegetables (150g)",
            "Chicken breast with brown rice and vegetables (200g)",
            "Tuna salad sandwich on whole wheat bread (150g)",
            "Tofu scramble with spinach and avocado (150g)",
            "Tofu and vegetable stir-fry with brown rice (150g)",
            "Black bean burger on a whole-wheat bun (150g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Lentil and quinoa salad (150g)",
            "Chickpea and vegetable curry (150g)",
            "Black bean burgers with sweet potato fries (150g)",
            "Vegetarian chili with a side salad (150g)",
            "Black bean burger with sweet potato fries (150g)",
            "Chicken stir-fry with brown rice (200g)",
            "Tuna salad sandwich on whole-wheat bread with a side of mixed greens (150g)",
            "Chicken breast with brown rice and steamed vegetables (200g)",
            "Chicken salad sandwich on whole-wheat bread with a side of mixed greens (200g)",
            "Lentil salad with quinoa and mixed greens (150g)",
            "Bean burrito with brown rice (150g)",
            "Lentil stew with brown rice and quinoa (150g)",
            "Black bean burger with whole wheat bun (150g)",
            "Quinoa salad with chicken and vegetables (200g)",
            "Chickpea salad with mixed greens (150g)",
            "Vegan lentil stew with brown rice (150g)",
            "Chicken and vegetable stir-fry with brown rice (200g)",
            "Tuna salad sandwich on whole-wheat bread (150g)",
            "Lentil and vegetable curry with brown rice (150g)",
            "Chicken breast and brown rice with vegetables (200g)",
            "Chicken salad sandwich on whole-wheat bread (200g)",
            "Tuna salad sandwich on whole-wheat bread with a side salad (150g)",
            "Chicken breast with brown rice and broccoli (200g)",
            "Black bean burger with a side salad (150g)"
        ],
        "snacks": [
            "Greek yogurt with fruit (100g)",
            "Cottage cheese with fruit (100g)",
            "Trail mix with nuts and seeds (150g)",
            "Fruit and nuts (100g)",
            "Apple with peanut butter (150g)",
            "Banana with almond butter (150g)",
            "Protein shake (150g)",
            "Apple slices with peanut butter (150g)",
            "Mixed nuts and seeds (150g)",
            "Trail mix (150g)",
            "Protein shake with banana (150g)",
            "Fruit salad with nuts (100g)",
            "Energy bar with nuts and seeds (150g)",
            "Trail mix with nuts and dried fruit (100g)",
            "Smoothie with protein powder and fruit (100g)",
            "Greek yogurt with nuts and seeds (100g)",
            "Protein shake with fruit (100g)",
            "Apple slices with almond butter (150g)",
            "Protein bar (150g)",
            "Fruit and nut mix (100g)",
            "Greek yogurt with fruit and nuts (100g)",
            "Trail mix with nuts and dried fruits (100g)",
            "Apple with almond butter (150g)",
            "Protein bar with nuts (150g)",
            "Trail mix with dried fruit and nuts (100g)",
            "Greek yogurt with berries and granola (100g)",
            "Protein shake with milk and banana (150g)",
            "Protein shake with almond butter (150g)",
            "Peanut butter and banana sandwich (150g)",
            "Fruit and nut smoothie (100g)",
            "Protein shake with fruit and spinach (100g)",
            "Protein smoothie with almond milk and banana (150g)",
            "Fruit and yogurt (100g)",
            "Nuts and seeds (150g)",
            "Whole-grain crackers with hummus (150g)",
            "Hummus with carrots and cucumber (150g)",
            "Fruit smoothie with plant-based milk (100g)",
            "Fruit with yogurt (100g)",
            "Almonds (150g)",
            "Fruit and vegetable salad (100g)"
        ],
        "night": [
            "Salmon with roasted vegetables (200g)",
            "Quinoa and vegetable bowl (150g)",
            "Chickpea and vegetable curry (150g)",
            "Lentil pasta with vegetables (150g)",
            "Chicken stir-fry with brown rice (200g)",
            "Tofu stir-fry with brown rice and vegetables (150g)",
            "Steak with roasted vegetables (200g)",
            "Black bean burgers with sweet potato fries (150g)",
            "Steak with sweet potato and asparagus (200g)",
            "Chicken breast with brown rice and vegetables (200g)",
            "Lentil and vegetable curry with brown rice (150g)",
            "Steak with sweet potato fries (200g)",
            "Lentil soup with whole-wheat bread (150g)",
            "Chickpea curry with brown rice (150g)",
            "Lentil stew with whole-wheat bread (150g)",
            "Tofu stir-fry with brown rice (150g)",
            "Vegan pasta with marinara sauce (150g)",
            "Black bean burgers on whole-wheat buns (150g)",
            "Vegan stir-fry with brown rice (150g)",
            "Salmon with sweet potato and broccoli (200g)",
            "Lentil stew with brown rice (150g)",
            "Steak with baked potato and green beans (200g)",
            "Salmon with roasted vegetables and quinoa (200g)",
            "Beef stir-fry with brown rice (150g)",
            "Chickpea and vegetable pasta (150g)",
            "Chickpea and vegetable curry with brown rice (150g)",
            "Steak with mashed potatoes and green beans (200g)",
            "Lentil and vegetable stew (150g)",
            "Lentil and vegetable stew with brown rice (150g)",
            "Grilled salmon with roasted vegetables (200g)",
            "Steak with sweet potato and broccoli (200g)",
            "Grilled chicken with roasted vegetables (200g)",
            "Turkey chili with sweet potato (150g)",
            "Chicken breast with sweet potato and broccoli (200g)",
            "Chickpea and vegetable pasta bake (150g)",
            "Lentil and vegetable curry with rice (150g)",
            "Tuna salad sandwich on whole-wheat bread (150g)",
            "Chickpea and vegetable stew (150g)",
            "Grilled chicken breast with quinoa and steamed vegetables (200g)",
            "Salmon with roasted sweet potatoes (200g)"
        ]
    }
};

module.exports = dietData;